Hw04 auth
benbrzezinski/node-homework-02-06-template pull request #3
Opened 2023-08-16 10:40 UTC by benbrzezinski

2023-08-16 13:25 UTC, RadziuMM requested changes

2023-08-16 13:25 UTC, RadziuMM commented on server/routes/controllers/users.js
> +    const body = Object.hasOwn(req.body, "username") ? req.body : null;
Nie zauważyłem że w zad 3 usunąłeś JOI do walidacji. Dlaczego? Ogólnie to powinno wygkądać tak że wszędzie gdzie kożystasz z req.bod powinna być walidacja (dla każdego endpointa odzielna schema) i walidowane całe req.body. Teraz teoretycznie mogę przesłać obok tych danych inne niepożdane atrybuty. No i teraz męczysz się z własną walidacją typu hasOwn itd....

Mniejwięcej coś takiego dla każdego endpointu z body:
```
 const { error } = createUserSchema.validate(req.body);
 if (error) {
   res.status(400).json({ error: validation.error.message });
 }
```

2023-08-16 13:25 UTC, RadziuMM commented on server/routes/api/authorization.js
> +    if (err || !user) {
Tu jeszcze brakuje sprawdzenia czy token w req jest taki sam jak user.token. Aktualnie mogę się wylogować i nadal  używać tokenu do sprawdzenia np /current

2023-08-16 17:09 UTC, benbrzezinski commented on server/routes/controllers/users.js
> +    const body = Object.hasOwn(req.body, "username") ? req.body : null;
Usunąłem Joi bo jest walidacja przez mongoose w models dla user i contact więc po co dwie walidację robić, sprawdzałem w insomni to normalnie działa? Tutaj hasOwn zrobiłem bo username jest tylko required dla register, więc nie pisałem required: true w model user tylko tak

2023-08-16 17:09 UTC, benbrzezinski commented on server/routes/api/authorization.js
> +    if (err || !user) {
Okej poprawię

2023-08-16 18:49 UTC, RadziuMM commented on server/routes/controllers/users.js
> +    const body = Object.hasOwn(req.body, "username") ? req.body : null;
Domyślam się że chciałeś uniknąć redundundacji, ale tu walidacja bardziej jest po to aby zabezpieczyć endpoint, aby ktoś ci nie grzebał przy API, po za tym teraz możesz na ten username przesłać byle co inta, plik, zdjęcie its co może tworzyć problemy

2023-08-16 19:03 UTC, benbrzezinski commented on server/routes/api/authorization.js
> +    if (err || !user) {
Okej w takim razie to dodam

2023-08-16 19:03 UTC, benbrzezinski commented on server/routes/controllers/users.js
> +    const body = Object.hasOwn(req.body, "username") ? req.body : null;
Okej w takim razie to dodam

2023-08-17 13:01 UTC, RadziuMM approved these changes

2023-08-17 16:03 UTC, merged